[package]
name = "mini-cluster-proto"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tonic = { version = "0.12", features = ["transport"] }
prost = "0.13"

[build-dependencies]
tonic-build = "0.12"
